<?
global $language;
	
$language = array();
	
$language[0] = "";
$language[1] = "zurück";
$language[2] = "Kontakt";
$language[3] = "* Pflichtangabe";
$language[4] = "Vorname";
$language[5] = "Name";
$language[6] = "Organisation";
$language[7] = "Straße";
$language[8] = "PLZ";
$language[9] = "Ort";
$language[10] = "E-Mail";
$language[11] = "bitte wählen";
$language[12] = "Ihre Nachricht";
$language[13] = "mehr";
$language[14] = "Absenden";
$language[15] = "<h1>Vielen Dank für Ihre Nachricht </h1><p>Wir melden uns schnellstmöglich bei Ihnen</p>";
$language[16] = "Passwort";
$language[21] = "Ich stimme zu, dass meine Angaben aus dem Kontaktformular zur Beantwortung meiner Anfrage erhoben und verarbeitet werden. Die Daten werden nach abgeschlossener Bearbeitung Ihrer Anfrage gelöscht.
Hinweis: Sie können Ihre Einwilligung jederzeit für die Zukunft per E-Mail an info@xxxx.de widerrufen.

Detaillierte Informationen zum Umgang mit Nutzerdaten finden Sie in unserer Datenschutzerklärung";
$language[22] = "Anmeldung";
$language[23] = "Bitte melden Sie sich mit ihren Login-Daten an, oder registrieren Sie sich.";
$language[24] = "Anmelden";
$language[25] = "Sie haben einen falschen Benutzernamen und/oder ein falsches Passwort eingegeben<br><br><a href=\"?loginreset=1\">Ich habe mein Passwort vergessen";
$language[26] = "Ihre Anfrage liegt zur Prüfung vor.";
$language[27] = "Sie haben bereits einen Zugang";
$language[28] = "Ihre E-Mail Adresse  ist nicht korrekt";
$language[29] = "Ihre Passwörter stimmen nicht überein";
$language[30] = "Ihre Passwort sollte aus mind. 6 Zeichen bestehen";
$language[31] = "<h2>Vielen Dank für Ihre Registrierung</h2><p>Ihre Anfrage wurde erfolgreich versandt.</p><p>Sie erhalten nun eine Bestätigungsmail. Bitte bestätigen Sie Ihre Anfrage durch Klick auf den Link in der E-Mail</p><p><b>Wenn Sie keine E-Mail in Ihrem Postfach vorfinden, dann prüfen Sie bitte auch Ihren Spam-Ordner.</b></p>";
$language[32] = "Die Anfrage wurde nicht gesendet. Es gab einen Fehler";
$language[33] = "Ich habe die Datenschutzerklärung zur Kenntnis genommen. Ich stimme zu, dass meine Angaben und Daten zur Beantwortung meiner Anfrage elektronisch erhoben und gespeichert werden. Hinweis: Sie können Ihre Einwilligung jederzeit für die Zukunft per E-Mail an <a href=\"mailto:globalhealth-forum@berlin-university-alliance.de\"><u>globalhealth-forum@berlin-university-alliance.de</u></a> widerrufen. Detaillierte Informationen zum Umgang mit Nutzerdaten finden Sie in unserer <a href=\"/datenschutz/\" target=\"_blank\"><u>Datenschutzerklärung</u></a>";
$language[34] = "Das Passwort sollte aus minimum 6 Zeichen bestehen.";
$language[35] = "Registrierung";
$language[36] = "Bitte füllen Sie alle mit * gekennzeichneten Felder aus.";
$language[37] = "Passwort bestätigen";
$language[38] = "Antrag Teilnehmer Login";
$language[39] = "<p><b>Vielen Dank für Ihre Registrierung im internen Werkstattbereich der Themenwerkstätten Urban Health.</b></p> <p> Um die Registrierung abzuschließen, bestätigen Sie bitte Ihre E-Mail-Adresse mit dem folgenden Link:</p><p> </p><p>#URL#</p><p> </p><p>Wir überprüfen Ihre Anfrage und melden uns schnellstmöglich bei Ihnen.</p><p>Ihr Team der Themenwerkstätten Urban Health<br>ein Projekt der Berlin University Alliance</p>";
$language[40] = "Vielen Dank für die Bestätigung Ihrer E-Mailadresse";
$language[41] = "<div class=\"alert alert-success\" role=\"alert\">Anfrage angenommen</div>
<p>Sie erhalten eine E-Mail mit einem Aktivierungslink für Ihr Konto.</p>
<div class=\"alert alert-success\" role=\"alert\">Request accepted</div>.
<p>You will receive an email with an activation link for your account.</p>";
$language[42] = "Aktivierungslink BUA Mitgliederbereich / Activation link BUA member area";
$language[43] = "Sie haben ein neues Passwort angefordert.
Bitte klicken Sie auf den folgenden Link oder kopieren Sie den kompletten Link in die Adresszeile Ihres Internetbrowsers.

You have requested a new password.
Please click on the following link or copy the complete link into the address line of your internet browser.";
$language[44] = "Ihre Mitgliedsdaten sind uns nicht bekannt.
We do not know your membership data.";
$language[45] = "Bitte geben Sie eine gültige E-Mail Adresse ein
Please enter a valid email address";
$language[46] = "Bitte füllen Sie alle Felder aus
Please fill in all fields";
$language[47] = "Bitte geben Sie ein neues Passwort ein.
Please enter a new password.";
$language[48] = "Das Passwort sollte mind. eine Zahl enthalten und insgesamt aus mind. 6 Zeichen bestehen.
The password should contain at least one number and a total of at least 6 characters.";
$language[49] = "Neues Passwort / new password";
$language[50] = "Neues Passwort wiederholen / Repeat new password";
$language[51] = "Passwort setzen - Set password";
$language[52] = "Abbrechen / Cancel";
$language[53] = "Die Passwörter stimmen nicht überein
The passwords do not match";
$language[54] = "Das Passwort muss mindestens aus #MIN# Zeichen bestehen.
The password must consist of at least #MIN# characters.";
$language[55] = "Das Passwort muss mindestens eine Zahl enthalten.
The password must contain at least one number.";
$language[56] = "Das Passwort muss mindestens einen Buchstaben enthalten.
The password must contain at least one letter.";
$language[57] = "Das Passwort wurde erfolgreich geändert.
The password has been changed successfully.";
$language[58] = "Position/ Funktion";
$language[59] = "Andere";
$language[60] = "Mein Kommentar";
$language[61] = "Liebe(r) {name}

wir haben Ihren Zugang zum global Health Portal frei geschaltet.

Sie können sich unter folgendem Link anmelden
{link}

Ihr Team der Themenwerkstätten Urban Health
ein Projekt der Berlin University Alliance";
$language[62] = "Titel";
$language[63] = "Anrede";
$language[64] = "Frau";
$language[65] = "Herr";
$language[66] = "Zurück zur Veranstaltungs Übersicht";
$language[67] = "Registrieren";
$language[68] = "Sie haben sich bereits für die Veranstaltung angemeldet";
	?>