<?
global $language;
	
$language = array();
	
$language[0] = "";
$language[1] = "back";
$language[2] = "Contact";
$language[3] = "* required fields";
$language[4] = "First name";
$language[5] = "Name";
$language[6] = "Organisation";
$language[7] = "street";
$language[8] = "ZIP Code";
$language[9] = "city";
$language[10] = "email";
$language[11] = "please select";
$language[12] = "Your message";
$language[13] = "more";
$language[14] = "send";
$language[15] = "<h1>Thank you for your request</h1><p>We will contact you as soon as possible</p>";
$language[16] = "Password";
$language[21] = "Ich stimme zu, dass meine Angaben aus dem Kontaktformular zur Beantwortung meiner Anfrage erhoben und verarbeitet werden. Die Daten werden nach abgeschlossener Bearbeitung Ihrer Anfrage gelöscht.
Hinweis: Sie können Ihre Einwilligung jederzeit für die Zukunft per E-Mail an info@xxxx.de widerrufen.

Detaillierte Informationen zum Umgang mit Nutzerdaten finden Sie in unserer Datenschutzerklärung";
$language[22] = "Log-in";
$language[23] = "Please log in with your login data or register.";
$language[24] = "Log in";
$language[25] = "You have entered an incorrect username and/or password<br><br><a href=\"?loginreset=1\">I have forgotten my password";
$language[26] = "Your request is available for review.";
$language[27] = "You already have an account";
$language[28] = "Your email address is not correct";
$language[29] = "Your passwords do not match";
$language[30] = "Your password should consist of at least 6 characters";
$language[31] = "<h2>Thank you for your registration</h2><p>We will get back to you as soon as possible</p>.";
$language[32] = "The request was not sent. There was an error";
$language[33] = "I have taken note of the privacy policy. I agree that my information and data will be collected and stored electronically to answer my request.  Note: You can revoke your consent for the future at any time by sending an email to <a href=\"mailto:globalhealth-forum@berlin-university-alliance.de\"><u>globalhealth-forum@berlin-university-alliance.de</u></a>.
Detailed information on the handling of user data can be found in our <a href=\"en/privacy/\" target=\"_blank\"><u>privacy policy</u></a>.";
$language[34] = "The password should consist of at least 6 characters.";
$language[35] = "Registration";
$language[36] = "Please fill in all of the fields marked with *.";
$language[37] = "Confirm password";
$language[38] = "Request participant login";
$language[39] = "<p><b>Vielen Dank für Ihre Registrierung im internen Werkstattbereich der Themenwerkstätten Urban Health.</b></p> <p> Um die Registrierung abzuschließen, bestätigen Sie bitte Ihre E-Mail-Adresse mit dem folgenden Link:</p><p> </p><p>#URL#</p><p> </p><p>Wir überprüfen Ihre Anfrage und melden uns schnellstmöglich bei Ihnen.</p><p>Ihr Team der Themenwerkstätten Urban Health<br>ein Projekt der Berlin University Alliance</p>";
$language[40] = "Thank you for confirming your email address";
$language[41] = "";
$language[42] = "";
$language[43] = "";
$language[44] = "";
$language[45] = "";
$language[46] = "";
$language[47] = "Please enter a new password.";
$language[48] = "";
$language[49] = "";
$language[50] = "";
$language[51] = "";
$language[52] = "";
$language[53] = "";
$language[54] = "";
$language[55] = "";
$language[56] = "";
$language[57] = "";
$language[58] = "Position/ Function";
$language[59] = "Other";
$language[60] = "My comment";
$language[61] = "";
$language[62] = "Title";
$language[63] = "Salutation";
$language[64] = "Ms.";
$language[65] = "Mr.";
$language[66] = "Back to the event overview";
$language[67] = "Registrieren";
$language[68] = "You have already registered for the event";
	?>