<?php  $nav = '
				<li class="nav-item n4n xx4xx" itemprop="url"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/ueber-uns/" class="nav-link " itemprop="name">Über uns</a></li>
				<li class="nav-item n2n xx2xx" itemprop="url"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/ihre-stimme/" class="nav-link " itemprop="name">Ihre Stimme</a></li>
				<li class="nav-item n19n xx19xx" itemprop="url"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/all-entries/" class="nav-link " itemprop="name">Stimmen</a></li>
				<li class="nav-item n20n xx20xx" itemprop="url"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/categories/" class="nav-link " itemprop="name">Categories</a></li>
				<li class="nav-item n22n xx22xx" itemprop="url"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/diary/" class="nav-link " itemprop="name">Diary</a></li>
				<li class="nav-item n23n xx23xx" itemprop="url"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/hashtag/" class="nav-link " itemprop="name">Hashtag</a></li>

';
?>
