<?php  
// VU: change menu
$nav = '
				<li class="nav-item n4n xx4xx" itemprop="url"><a href="http://localhost/berlinforschtmit/de/all-entries/" class="nav-link " itemprop="name">All entries</a></li>
				<li class="nav-item n2n xx2xx" itemprop="url"><a href="http://localhost/berlinforschtmit/de/categories/" class="nav-link " itemprop="name">Categories</a></li>
				<li class="nav-item n2n xx2xx" itemprop="url"><a href="http://localhost/berlinforschtmit/de/hashtag/" class="nav-link " itemprop="name">Hashtag</a></li>
				<li class="nav-item n18n xx18xx" itemprop="url"><a href="http://localhost/berlinforschtmit/de/diary/" class="nav-link " itemprop="name">DIARY</a></li>

';
// END
?>
