<?php  $nav = '
				<li class="nav-item n4n xx4xx" itemprop="url"><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/ueber-uns/" class="nav-link " itemprop="name">Über uns</a></li>
				<li class="nav-item n2n xx2xx" itemprop="url"><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/ihre-stimme/" class="nav-link " itemprop="name">Ihre Stimme</a></li>
				<li class="nav-item n18n xx18xx" itemprop="url"><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/kontakt/" class="nav-link " itemprop="name">Kontakt</a></li>

';
?>
