
<?php  $output .= '<ul class="sitemap">

		<li class="parent n__4"><a href="https://bua.morpheus-cms.de/berlinforschtmit/ueber-uns/">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a href="https://bua.morpheus-cms.de/berlinforschtmit/ihre-stimme/">Ihre Stimme</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__18"><a href="https://bua.morpheus-cms.de/berlinforschtmit/kontakt/">Kontakt</a>
		 	<ul class="sub-menu3"></li>
</ul>
';
?>
</ul>