
<?php  $output .= '<ul class="sitemap">

		<li class="parent n__1"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/home/">Home</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__4"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/ueber-das-projekt/">Über das Projekt</a>
		 	<ul class="sub-menu2"></li>
</li>
</li>
				<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/ueber-das-projekt/ueber-uns/" title="Über uns">Über uns</a></li>
</li>
</li>
				<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/ueber-das-projekt/das-projekt/" title="Das Projekt">Das Projekt</a></ul>
		</li>

		<li class="parent n__2"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/deine-stimme/">Deine Stimme</a>
		 	<ul class="sub-menu3"></li>
</ul>
';
?>
</ul>