<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/ueber-uns/">Über uns</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/deine-stimme/">Deine Stimme</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/impressum/">Impressum</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/datenschutz/">Datenschutz</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/cookie/">Cookie-Einstellungen</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/all-entries/">Stimmen</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/categories/">Categories</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/diary/">Diary</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/hashtag/">Hashtag</a></strong></li>
</ul>'; ?>