<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/home/">Home</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong>Über das Projekt</strong></li>
					<li class="sn"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/ueber-das-projekt/ueber-uns/">Über uns</a></li>
					<li class="sn"><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/ueber-das-projekt/das-projekt/">Das Projekt</a></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/deine-stimme/">Deine Stimme</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/impressum/">Impressum</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/datenschutz/">Datenschutz</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/cookie/">Cookie-Einstellungen</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/">Stimmen</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/">Chart</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/">Diary</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/">Hashtag</a></strong></li>
</ul>'; ?>