<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/ueber-uns/">Über uns</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/ihre-stimme/">Ihre Stimme</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/kontakt/">Kontakt</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/impressum/">Impressum</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/datenschutz/">Datenschutz</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/cookie/">Cookie-Einstellungen</a></strong></li>
</ul>'; ?>