
<?php  $structure_edit_mode = '<ul class="sitemap_edit"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__1"><a data-clipboard-text="anker:1" class="intLink">Home</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="anker:4" class="intLink">Über das Projekt</a>
		 	<ul class="sub-menu2">				<li><a data-clipboard-text="<anker:25:>" class="intLink">Über uns</a>				<li><a data-clipboard-text="<anker:24:>" class="intLink">Das Projekt</a></ul>
		</li>

		<li class="parent n__2"><a data-clipboard-text="anker:2" class="intLink">Deine Stimme</a>
		 	<ul class="sub-menu3"></li>
		<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
			<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/cookie/" title="cookie-einstellungen"><strong>Cookie-Einstellungen</strong></a></li>
	</ul>
';
?>
</ul>