
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__4"><a data-clipboard-text="<a:4:>Link_Name</a>" class="intLink">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a data-clipboard-text="<a:2:>Link_Name</a>" class="intLink">Ihre Stimme</a>
		 	<ul class="sub-menu2"></li>
		<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
			<li><a href="http://localhost:8888/berlinforscht/bua_berlinforschtmit/de/cookie/" title="cookie-einstellungen"><strong>Cookie-Einstellungen</strong></a></li>
	</ul>
';
?>
</ul>