
<?php  $structure_edit_mode = '<ul class="sitemap_edit"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__4"><a data-clipboard-text="anker:4" class="intLink">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a data-clipboard-text="anker:2" class="intLink">Ihre Stimme</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__18"><a data-clipboard-text="anker:18" class="intLink">Kontakt</a>
		 	<ul class="sub-menu3"></li>
		<li><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
			<li><a href="https://bua.morpheus-cms.de/berlinforschtmit/de/cookie/" title="cookie-einstellungen"><strong>Cookie-Einstellungen</strong></a></li>
	</ul>
';
?>
</ul>